name: OneCycleLR
scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: true
  max_lr: 0.1
  epochs: ${trainer.max_epochs}
  pct_start: 0.1
  verbose: False
kwargs:
  interval: "step"
  frequency: 1
