name: ReduceLROnPlateau
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
kwargs:
  interval: "epoch"
  frequency: ${trainer.check_val_every_n_epoch}
  monitor: "val/loss"
  strict: True